CREATE TABLE IF NOT EXISTS device_telemetries (
    id BIGSERIAL,
    device_id VARCHAR(64) NOT NULL,
    ts BIGINT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    battery DOUBLE PRECISION,
    ax DOUBLE PRECISION NOT NULL,
    ay DOUBLE PRECISION NOT NULL,
    az DOUBLE PRECISION NOT NULL
);