CREATE UNLOGGED TABLE IF NOT EXISTS device_telemetries (
    id BIGSERIAL,
    device_id VARCHAR(64) NOT NULL,
    ts BIGINT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    battery DOUBLE PRECISION,
    ax DOUBLE PRECISION NOT NULL,
    ay DOUBLE PRECISION NOT NULL,
    az DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_device_ts ON device_telemetries (device_id, ts DESC);