services:
  nginx:
    image: nginx:alpine
    ports:
     - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
      - api-3
    deploy:
      resources:
        limits:
          memory: 20m
          cpus: "0.20"
  
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres500user
      POSTGRES_PASSWORD: postgres500pass
      POSTGRES_DB: postgres500db
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    command: >
      postgres
        -c shared_buffers=32MB
        -c work_mem=4MB
        -c max_connections=50
        -c checkpoint_completion_target=0.9
        -c wal_buffers=8MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres500user -d postgres500db"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 140m
          cpus: "0.60"

  api-1:
    build: .
    environment:
      INSTANCE_ID: api-1
      STORAGE_BACKEND: postgres
      DATABASE_URL: postgres://postgres500user:postgres500pass@postgres:5432/postgres500db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 110m
          cpus: "0.40"

  api-2:
    build: .
    environment:
      INSTANCE_ID: api-2
      STORAGE_BACKEND: postgres
      DATABASE_URL: postgres://postgres500user:postgres500pass@postgres:5432/postgres500db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 110m
          cpus: "0.40"

  api-3:
    build: .
    environment:
      INSTANCE_ID: api-3
      STORAGE_BACKEND: postgres
      DATABASE_URL: postgres://postgres500user:postgres500pass@postgres:5432/postgres500db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 110m
          cpus: "0.40"